[package]
name = "ChainProfile"
version = "0.0.1"
upgrade_policy = "compatible"

[addresses]
chain_profile = "0x0"
one = "0x2"

[dependencies]
OneChain = { git = "https://github.com/one-chain-labs/onechain.git", subdir = "crates/one-framework/packages/one-framework", rev = "testnet" }
